**Melakukan Koneksi Dengan Google Drive, dan memanggil file dataset**

In [ ]:
# NAMA    : Adi Setyo Nugroho 
# NRP     : 6025201003
# KELAS   : Topik Dalam Data Mining - A
# TUGAS   : Ukur Performa Klasifikasi

# from google.colab import drive
# drive.mount('/content/drive')

train_path = r'/content/drive/My Drive/Colab Notebooks/Data Mining/Tugas 3/data_training.csv'
test_path = r'/content/drive/My Drive/Colab Notebooks/Data Mining/Tugas 3/data_testing.csv'

**Membaca data training dan analisis data**

In [ ]:
# library untuk baca excel
import pandas as pd
import numpy as np

# membaca data
data_training = pd.read_csv(train_path)
data_testing = pd.read_csv(test_path)

**Persiapan data dan preprocessing**

In [ ]:
# memisahkan antara hasil dan atribut
# array berisi nilai
hasil_train = data_training['diagnosis'].to_numpy()
atr_train = data_training[['radius_mean', 'texture_mean', 'perimeter_mean', 'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean', 'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean', 'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se', 'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se', 'fractal_dimension_se', 'radius_worst', 'texture_worst', 'perimeter_worst', 'area_worst', 'smoothness_worst', 'compactness_worst', 'concavity_worst', 'concave points_worst', 'symmetry_worst', 'fractal_dimension_worst']].to_numpy()
atr_test = data_testing[['radius_mean', 'texture_mean', 'perimeter_mean', 'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean', 'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean', 'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se', 'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se', 'fractal_dimension_se', 'radius_worst', 'texture_worst', 'perimeter_worst', 'area_worst', 'smoothness_worst', 'compactness_worst', 'concavity_worst', 'concave points_worst', 'symmetry_worst', 'fractal_dimension_worst']].to_numpy()

# library untuk normalisasi data
# range data dirubah menjadi antara 0 dan 1
from sklearn.preprocessing import MinMaxScaler

# normalisasi
scaler = MinMaxScaler(feature_range=(0,1))
atr_train = scaler.fit_transform(atr_train)
atr_test = scaler.fit_transform(atr_test)

print(atr_train)
print(atr_test)

[[0.52202342 0.0226581  0.53878256 ... 0.91422666 0.59838328 0.41821525]
 [0.65279538 0.27257355 0.61145489 ... 0.6407165  0.23343849 0.22201064]
 [0.60819099 0.3902604  0.59058857 ... 0.83706511 0.40358833 0.21255499]
 ...
 [0.45156876 0.62123774 0.434451   ... 0.48846021 0.1285489  0.15096198]
 [0.65431598 0.66351031 0.6632609  ... 0.91284878 0.49704259 0.45170399]
 [0.00349739 0.50152181 0.         ... 0.         0.25729495 0.09967825]]
[[0.35775474 1.         0.36583512 ... 0.58831615 0.79981911 0.92511116]
 [0.36438071 0.55681818 0.35208348 ... 0.55292096 0.44136268 0.31734145]
 [0.43300677 0.58971292 0.44440605 ... 0.71237113 0.64546277 0.69225369]
 ...
 [0.28628899 0.45454545 0.26826066 ... 0.17226804 0.12722339 0.07781418]
 [0.36911354 0.784689   0.37046507 ... 0.55463918 0.52939403 0.39866604]
 [0.11756354 0.60944976 0.11277728 ... 0.22395189 0.39583961 0.43377018]]


**Membuat model, membuat prediksi, dan melakukan klasifikasi dengan model terbaik**

In [ ]:
# library untuk membuat model
from sklearn.model_selection import KFold

# library untuk decission tree
from sklearn.tree import DecisionTreeClassifier

# nilai klasik untuk random_state = 0 dan 42
# n_splits menentukan banyak iterasi/epoch
kfold = KFold(n_splits = 10, random_state = None, shuffle=False)
best_dTree = DecisionTreeClassifier()
score = 0
nomor_model = 0
y_pred_test = []

i = 1
for train_index, test_index in kfold.split(atr_train):
  
  # print(f"Epoch {i} \n")
  # print(f"Train Index : {train_index} \n")
  # print(f"Test Index  : {test_index}")

  X_train, X_test, y_train, y_test = atr_train[train_index], atr_train[test_index], hasil_train[train_index], hasil_train[test_index]
  
  # fit -> untuk melakukan train pada decission tree
  best_dTree.fit(X_train, y_train)
  y_predict = best_dTree.predict(X_test)

  # perhitungan akurasi model
  akurasi = best_dTree.score(X_test, y_test)

  print(f'Model ke {i}')
  print(f'Akurasi : {akurasi}')
  print(f'Hasil Prediksi (dari data training): {y_predict}\n')

  # memilih model dengan akurasi terbaik
  if score < akurasi:
    score = akurasi
    nomor_model = i

    # melakukan klasifikasi data_testing.csv menggunakan model dengan akurasi terbaik
    y_pred_test = best_dTree.predict(atr_test)
  elif score == akurasi:
    pass
  elif score > akurasi:
    pass

  i+=1

Model ke 1
Akurasi : 0.9111111111111111
Hasil Prediksi (dari data training): ['M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'B' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'B' 'M' 'B' 'M' 'B' 'M' 'B' 'B' 'M' 'B' 'M' 'M' 'B' 'B' 'B'
 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'M' 'B']

Model ke 2
Akurasi : 0.9333333333333333
Hasil Prediksi (dari data training): ['B' 'B' 'M' 'M' 'B' 'B' 'B' 'M' 'M' 'B' 'M' 'B' 'B' 'M' 'M' 'B' 'B' 'M'
 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'B' 'M' 'M' 'M' 'B' 'M' 'B' 'M' 'B' 'B' 'B'
 'M' 'M' 'B' 'B' 'M' 'B' 'M' 'M' 'M']

Model ke 3
Akurasi : 0.9555555555555556
Hasil Prediksi (dari data training): ['M' 'B' 'M' 'M' 'M' 'B' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'M' 'B' 'B' 'B' 'M'
 'B' 'M' 'M' 'B' 'B' 'M' 'B' 'B' 'M' 'M' 'B' 'M' 'B' 'B' 'B' 'B' 'M' 'B'
 'B' 'B' 'B' 'B' 'M' 'B' 'M' 'M' 'M']

Model ke 4
Akurasi : 0.9333333333333333
Hasil Prediksi (dari data training): ['M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'M'
 'B' 'M' 'B' 'B' 'M' 'B' 'B' 'M' 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'B'

**Cetak hasil klasifikasi data testing menggunakan model terbaik**

In [ ]:
print(f'Klasifikasi menggunakan nomor model ke - {nomor_model}')
print(f'Dengan akurasi : {score}')
print(y_pred_test)

Klasifikasi menggunakan nomor model ke - 8
Dengan akurasi : 1.0
['M' 'B' 'M' 'M' 'B' 'B' 'B' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'B' 'M' 'B' 'M'
 'B' 'M' 'B' 'M' 'B' 'M' 'B' 'M' 'B' 'B' 'M' 'M' 'B' 'M' 'B' 'M' 'M' 'M'
 'B' 'M' 'M' 'M' 'B' 'B' 'M' 'M' 'B' 'M' 'M' 'M' 'B' 'B' 'B' 'M' 'M' 'B'
 'B' 'B' 'B' 'M' 'B' 'B' 'M' 'B' 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'M' 'M' 'M'
 'B' 'M' 'M' 'B' 'B' 'M' 'M' 'B' 'M' 'M' 'B' 'M' 'M' 'B' 'M' 'M' 'B' 'B'
 'M' 'B' 'B' 'M' 'M' 'M' 'M' 'M' 'B' 'M' 'M' 'B' 'M' 'B' 'M' 'B' 'M' 'M'
 'B' 'M' 'B' 'B' 'B' 'M' 'B' 'M' 'M' 'B' 'M' 'B']


**Membuat file excel baru**

In [ ]:
# membuat data frame baru
y_df = pd.DataFrame(y_pred_test)

ID = data_test.iloc[:, 0]
ID = pd.DataFrame(ID)

hasil = pd.concat([ID, y_df], axis=1)
hasil.to_csv('hasil_klasifikasi.csv')